/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    products: Product;
    posts: Post;
    messages: Message;
    'activity-log': ActivityLog;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    messages: MessagesSelect<false> | MessagesSelect<true>;
    'activity-log': ActivityLogSelect<false> | ActivityLogSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('id' | 'en') | ('id' | 'en')[];
  globals: {
    'site-settings': SiteSetting;
    'home-page': HomePage;
    'about-page': AboutPage;
    'info-pages': InfoPage;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    'home-page': HomePageSelect<false> | HomePageSelect<true>;
    'about-page': AboutPageSelect<false> | AboutPageSelect<true>;
    'info-pages': InfoPagesSelect<false> | InfoPagesSelect<true>;
  };
  locale: 'id' | 'en';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    username: string;
  };
  login: {
    password: string;
    username: string;
  };
  registerFirstUser: {
    password: string;
    username: string;
  };
  unlock: {
    username: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email?: string | null;
  username: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  resetPasswordRequestedAt?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Deskripsi singkat gambar (untuk aksesibilitas & SEO).
   */
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  title: string;
  /**
   * Huruf kecil, angka, dan tanda hubung. Contoh: artic-600ml
   */
  slug: string;
  /**
   * Angka kecil tampil lebih dulu.
   */
  order?: number | null;
  image: number | Media;
  /**
   * Satu kalimat di bawah nama produk.
   */
  tagline?: string | null;
  /**
   * Contoh: Volume = 600 ml. Isi hanya data yang benar; belum tahu, tulis "Menyusul".
   */
  specs?:
    | {
        label: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  /**
   * Huruf kecil, tanpa spasi, dipakai di URL artikel.
   */
  slug: string;
  publishedAt?: string | null;
  cover?: (number | null) | Media;
  /**
   * Ringkasan 1-2 kalimat untuk daftar artikel.
   */
  excerpt?: string | null;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "messages".
 */
export interface Message {
  id: number;
  company: string;
  name: string;
  contact: string;
  product?: string | null;
  volume?: string | null;
  message?: string | null;
  /**
   * Bahasa halaman saat pesan dikirim.
   */
  locale?: string | null;
  handled?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Riwayat perubahan di panel admin: siapa, kapan, apa. Hanya bisa dibaca.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "activity-log".
 */
export interface ActivityLog {
  id: number;
  actor?: string | null;
  action?: ('login' | 'create' | 'update' | 'delete') | null;
  area?: string | null;
  item?: string | null;
  fields?: string | null;
  summary?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'messages';
        value: number | Message;
      } | null)
    | ({
        relationTo: 'activity-log';
        value: number | ActivityLog;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  username?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  resetPasswordRequestedAt?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  order?: T;
  image?: T;
  tagline?: T;
  specs?:
    | T
    | {
        label?: T;
        value?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  publishedAt?: T;
  cover?: T;
  excerpt?: T;
  content?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "messages_select".
 */
export interface MessagesSelect<T extends boolean = true> {
  company?: T;
  name?: T;
  contact?: T;
  product?: T;
  volume?: T;
  message?: T;
  locale?: T;
  handled?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "activity-log_select".
 */
export interface ActivityLogSelect<T extends boolean = true> {
  actor?: T;
  action?: T;
  area?: T;
  item?: T;
  fields?: T;
  summary?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  companyName: string;
  brandName: string;
  address: string;
  /**
   * Harus diawali https://
   */
  mapsUrl?: string | null;
  phone?: string | null;
  email?: string | null;
  /**
   * Contoh: 08.00 - 16.00 WIB
   */
  hours?: string | null;
  /**
   * Contoh: https://www.instagram.com/articwater.id/
   */
  instagramUrl?: string | null;
  /**
   * Boleh ditulis 0812-3456-7890 atau +62 812 3456 7890; situs mengubahnya ke format yang benar.
   */
  whatsapp?: string | null;
  /**
   * Hanya isi yang sudah resmi & valid. Contoh: "BPOM MD 123456".
   */
  certifications?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Menampilkan "Website oleh IDNX" di bagian bawah situs. Matikan jika diminta.
   */
  showDeveloperCredit?: boolean | null;
  footerDescription?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page".
 */
export interface HomePage {
  id: number;
  hero: {
    /**
     * Pilih tampilan bagian paling atas Beranda. Perubahan langsung tampil setelah disimpan.
     */
    style?: ('banner' | 'lake' | 'mountain' | 'forest' | 'photo') | null;
    eyebrow?: string | null;
    title: string;
    description?: string | null;
    /**
     * Hanya fakta yang benar dan bisa dibuktikan.
     */
    facts?:
      | {
          value: string;
          label: string;
          id?: string | null;
        }[]
      | null;
  };
  videoSection?: {
    enabled?: boolean | null;
    eyebrow?: string | null;
    title?: string | null;
    text?: string | null;
  };
  trust?: {
    title?: string | null;
    /**
     * Kosongkan semua baris untuk menyembunyikan bar ini.
     */
    items?:
      | {
          label: string;
          status: string;
          id?: string | null;
        }[]
      | null;
  };
  productsSection?: {
    eyebrow?: string | null;
    title?: string | null;
    description?: string | null;
  };
  benefits?: {
    eyebrow?: string | null;
    title?: string | null;
    items?:
      | {
          icon: 'package' | 'zap' | 'truck' | 'headset';
          title: string;
          text: string;
          id?: string | null;
        }[]
      | null;
  };
  segments?: {
    eyebrow?: string | null;
    title?: string | null;
    items?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
  };
  process?: {
    eyebrow?: string | null;
    title?: string | null;
    steps?:
      | {
          title: string;
          text: string;
          id?: string | null;
        }[]
      | null;
  };
  quote?: {
    eyebrow?: string | null;
    title?: string | null;
    description?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-page".
 */
export interface AboutPage {
  id: number;
  about?: {
    eyebrow?: string | null;
    title?: string | null;
    description?: string | null;
    storyTitle?: string | null;
    story?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
    expertiseTitle?: string | null;
    expertise?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
    visionTitle?: string | null;
    vision?: string | null;
    missionTitle?: string | null;
    mission?: string | null;
    valuesTitle?: string | null;
    values?:
      | {
          title: string;
          text: string;
          id?: string | null;
        }[]
      | null;
    legalTitle?: string | null;
    ctaTitle?: string | null;
    ctaText?: string | null;
  };
  contact?: {
    title?: string | null;
    description?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "info-pages".
 */
export interface InfoPage {
  id: number;
  quality?: {
    eyebrow?: string | null;
    title?: string | null;
    description?: string | null;
    pillarsTitle?: string | null;
    /**
     * Hanya tulis hal yang benar dan bisa dibuktikan.
     */
    pillars?:
      | {
          title: string;
          text: string;
          id?: string | null;
        }[]
      | null;
    legalTitle?: string | null;
    legalNote?: string | null;
    ctaTitle?: string | null;
    ctaText?: string | null;
  };
  orderPage?: {
    eyebrow?: string | null;
    title?: string | null;
    description?: string | null;
    faqTitle?: string | null;
    faqs?:
      | {
          q: string;
          a: string;
          id?: string | null;
        }[]
      | null;
    ctaTitle?: string | null;
    ctaText?: string | null;
  };
  privacy?: {
    title?: string | null;
    updated?: string | null;
    intro?: string | null;
    /**
     * Tinjau dengan pihak legal PT sebelum tayang. Ubah tanggal pembaruan setiap ada perubahan.
     */
    sections?:
      | {
          title: string;
          text: string;
          id?: string | null;
        }[]
      | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  companyName?: T;
  brandName?: T;
  address?: T;
  mapsUrl?: T;
  phone?: T;
  email?: T;
  hours?: T;
  instagramUrl?: T;
  whatsapp?: T;
  certifications?:
    | T
    | {
        text?: T;
        id?: T;
      };
  showDeveloperCredit?: T;
  footerDescription?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page_select".
 */
export interface HomePageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        style?: T;
        eyebrow?: T;
        title?: T;
        description?: T;
        facts?:
          | T
          | {
              value?: T;
              label?: T;
              id?: T;
            };
      };
  videoSection?:
    | T
    | {
        enabled?: T;
        eyebrow?: T;
        title?: T;
        text?: T;
      };
  trust?:
    | T
    | {
        title?: T;
        items?:
          | T
          | {
              label?: T;
              status?: T;
              id?: T;
            };
      };
  productsSection?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        description?: T;
      };
  benefits?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        items?:
          | T
          | {
              icon?: T;
              title?: T;
              text?: T;
              id?: T;
            };
      };
  segments?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        items?:
          | T
          | {
              text?: T;
              id?: T;
            };
      };
  process?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        steps?:
          | T
          | {
              title?: T;
              text?: T;
              id?: T;
            };
      };
  quote?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        description?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-page_select".
 */
export interface AboutPageSelect<T extends boolean = true> {
  about?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        description?: T;
        storyTitle?: T;
        story?:
          | T
          | {
              text?: T;
              id?: T;
            };
        expertiseTitle?: T;
        expertise?:
          | T
          | {
              text?: T;
              id?: T;
            };
        visionTitle?: T;
        vision?: T;
        missionTitle?: T;
        mission?: T;
        valuesTitle?: T;
        values?:
          | T
          | {
              title?: T;
              text?: T;
              id?: T;
            };
        legalTitle?: T;
        ctaTitle?: T;
        ctaText?: T;
      };
  contact?:
    | T
    | {
        title?: T;
        description?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "info-pages_select".
 */
export interface InfoPagesSelect<T extends boolean = true> {
  quality?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        description?: T;
        pillarsTitle?: T;
        pillars?:
          | T
          | {
              title?: T;
              text?: T;
              id?: T;
            };
        legalTitle?: T;
        legalNote?: T;
        ctaTitle?: T;
        ctaText?: T;
      };
  orderPage?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        description?: T;
        faqTitle?: T;
        faqs?:
          | T
          | {
              q?: T;
              a?: T;
              id?: T;
            };
        ctaTitle?: T;
        ctaText?: T;
      };
  privacy?:
    | T
    | {
        title?: T;
        updated?: T;
        intro?: T;
        sections?:
          | T
          | {
              title?: T;
              text?: T;
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}